#json.schemastore.org/detekt-1.22.0.json
comments:
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true

formatting:
  Filename:
    active: false

style:
  MagicNumber:
    active: false
